# Generated by Django 4.1.1 on 2022-10-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_date_joined_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
