# Generated by Django 4.1.1 on 2022-10-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_delete_profesion_persona_especializacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='especializacion',
        ),
    ]
