# Generated by Django 4.1.1 on 2022-10-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patients_cc_alter_patients_direction_and_more'),
        ('clinic_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Cc',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Direction',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Eps',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Surname',
        ),
        migrations.RemoveField(
            model_name='history',
            name='email',
        ),
        migrations.RemoveField(
            model_name='history',
            name='gender',
        ),
        migrations.AlterField(
            model_name='history',
            name='Doctor_concept',
            field=models.TextField(max_length=1000, verbose_name='Concepto del doctor'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Occupation',
            field=models.CharField(max_length=100, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Rh',
            field=models.CharField(max_length=2, verbose_name='Rh'),
        ),
        migrations.AlterField(
            model_name='history',
            name='current_illness',
            field=models.CharField(max_length=100, verbose_name='Enfermdad actual'),
        ),
        migrations.AlterField(
            model_name='history',
            name='hour_entry_finish',
            field=models.DateTimeField(max_length=100, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='history',
            name='reason_for_consultation',
            field=models.CharField(max_length=1000, verbose_name='Motivo de la consulta'),
        ),
    ]
