# Generated by Django 4.1.1 on 2022-10-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0004_alter_history_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Name',
            new_name='Name_patients',
        ),
        migrations.AlterField(
            model_name='history',
            name='Doctor_concept',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Concepto del doctor'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Rh',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Rh'),
        ),
        migrations.AlterField(
            model_name='history',
            name='current_illness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enfermdad actual'),
        ),
        migrations.AlterField(
            model_name='history',
            name='hour_entry_finish',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='history',
            name='reason_for_consultation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo de la consulta'),
        ),
    ]
