# Generated by Django 4.1.1 on 2022-11-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0006_alter_history_rh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Rh',
        ),
    ]
