# Generated by Django 4.1.1 on 2022-10-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0004_alter_patients_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('specialty', models.CharField(blank=True, choices=[('C Y D', 'Crecimiento y desarrollo'), ('V', 'Vacunacion')], max_length=50, null=True, verbose_name='consulta')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctors', verbose_name='Doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Paciente')),
            ],
        ),
    ]
