# Generated by Django 4.1.1 on 2022-10-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('eps', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.medico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.paciente')),
            ],
        ),
    ]
