# Generated by Django 4.1.1 on 2022-10-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0003_alter_patients_gender'),
        ('Medical_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctors', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='eps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eps'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='specialty',
            field=models.CharField(blank=True, choices=[('C Y D', 'Crecimiento y desarrollo'), ('V', 'Vacunacion')], max_length=50, null=True, verbose_name='consulta'),
        ),
    ]
