# Generated by Django 4.1.1 on 2022-10-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_appointment', '0002_alter_quotes_doctors_alter_quotes_eps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='eps',
        ),
    ]
