# Generated by Django 4.1.1 on 2022-10-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='profesion',
        ),
    ]
