# Generated by Django 4.1.1 on 2022-10-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='Genero'),
        ),
    ]
