# Generated by Django 4.1.1 on 2022-10-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_remove_medico_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especializacion',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
