# Generated by Django 4.1.1 on 2022-10-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_doctors_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Cc',
            new_name='identification_number',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especializacion'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cumpleaños'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='meets_the_profile',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cumple oon el perfil'),
        ),
    ]
