# Generated by Django 4.1.1 on 2022-10-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_rename_cc_doctors_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='type_identification',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='tipo de identificacion'),
        ),
    ]
