# Generated by Django 4.1.1 on 2022-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_doctors_type_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Telefono'),
        ),
    ]
