# Generated by Django 4.1.1 on 2022-10-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0002_profesion_alter_persona_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_profesional', models.CharField(max_length=30)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.profesion')),
            ],
        ),
    ]
