# Generated by Django 4.1.1 on 2022-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Cc',
            field=models.CharField(max_length=11, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Direction',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Eps',
            field=models.CharField(max_length=100, verbose_name='Eps'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Phone',
            field=models.CharField(max_length=13, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Surname',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.CharField(max_length=3, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cumpleaños'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=4, verbose_name='Genero'),
        ),
    ]
