# Generated by Django 4.1.1 on 2022-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_patients_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Eps',
            field=models.CharField(choices=[('S', 'SANITAS'), ('N', 'NUEVA EPS'), ('F', 'FAMISANAR'), ('CP', 'CAPITAL SALUD'), ('A', 'ALIANSALUD'), ('C', 'COMPENSAR'), ('CO', 'COMMEVAEPS'), ('SA', 'SALUD TOTAL'), ('SU', 'SURA'), ('SO', 'SOS'), ('FU', 'FUNDACION SALUD MIA')], max_length=50, verbose_name='Eps'),
        ),
    ]
