# Generated by Django 4.1.1 on 2022-10-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_patients_eps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='Cc',
            new_name='identification_number',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.AlterField(
            model_name='patients',
            name='Eps',
            field=models.CharField(max_length=50, verbose_name='Eps'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='Genero'),
        ),
    ]
