# Generated by Django 4.1.1 on 2022-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patients_type_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Phone',
            field=models.CharField(max_length=18, verbose_name='Telefono'),
        ),
    ]
