# Generated by Django 4.1.1 on 2022-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_alter_patients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Rh',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Rh'),
        ),
    ]
