# Generated by Django 4.1.1 on 2022-10-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('Surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('Cc', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Cedula')),
                ('Phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefono')),
                ('Direction', models.CharField(blank=True, max_length=50, null=True, verbose_name='direccion')),
                ('gender', models.CharField(default='M', max_length=1, verbose_name='Genero')),
                ('Eps', models.CharField(blank=True, choices=[('S', 'SANITAS'), ('N', 'NUEVA EPS'), ('F', 'FAMISANAR'), ('CP', 'CAPITAL SALUD'), ('A', 'ALIANSALUD'), ('C', 'COMPENSAR'), ('CO', 'COMMEVAEPS'), ('SA', 'SALUD TOTAL'), ('SU', 'SURA'), ('SO', 'SOS'), ('FU', 'FUNDACION SALUD MIA')], max_length=100, null=True, verbose_name='EPS')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Coreeo electronico')),
                ('Professional_card', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Tarjeta profesional')),
                ('Specialization', models.CharField(blank=True, choices=[('J', 'JEFE DE ENFERMERIA'), ('E', 'ENFERMERA')], max_length=100, null=True, verbose_name='Especializacion')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de cumpleaños')),
                ('meets_the_profile', models.BooleanField(verbose_name='Cumple con el perfil')),
            ],
        ),
    ]
