# Generated by Django 4.1.1 on 2022-10-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='gender',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], max_length=1, verbose_name='Genero'),
        ),
    ]
