# Generated by Django 4.1.1 on 2022-10-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0004_alter_patients_eps'),
        ('Nurse', '0002_alter_nurses_gender'),
        ('Doctor', '0003_alter_doctors_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('Biological', models.CharField(blank=True, max_length=50, null=True, verbose_name='Biologico')),
                ('Dose', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dosis')),
                ('Vaccine_date', models.DateField(blank=True, null=True, verbose_name='Fecha de la vacuna')),
                ('Factory', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabricante')),
                ('Lot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('Eps', models.CharField(blank=True, choices=[('S', 'SANITAS'), ('N', 'NUEVA EPS'), ('F', 'FAMISANAR'), ('CP', 'CAPITAL SALUD'), ('A', 'ALIANSALUD'), ('C', 'COMPENSAR'), ('CO', 'COMMEVAEPS'), ('SA', 'SALUD TOTAL'), ('SU', 'SURA'), ('SO', 'SOS'), ('FU', 'FUNDACION SALUD MIA')], max_length=100, null=True, verbose_name='Ips vacunadora')),
                ('Data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Datos del paciente')),
                ('Vaccinator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nurse.nurses', verbose_name='Nombre del vacunador')),
            ],
        ),
        migrations.CreateModel(
            name='Growth_and_development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_joined', models.DateTimeField(auto_now_add=True)),
                ('Weight', models.CharField(blank=True, max_length=3, null=True, verbose_name='Peso')),
                ('stature', models.CharField(blank=True, max_length=3, null=True, verbose_name='Estatura')),
                ('IMC', models.CharField(blank=True, max_length=3, null=True, verbose_name='Imc')),
                ('Temperature', models.CharField(blank=True, max_length=2, null=True, verbose_name='Temperatura')),
                ('Pulse', models.CharField(blank=True, max_length=3, null=True, verbose_name='Pulso')),
                ('Breathing_frequency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Frecuencia respiratoria')),
                ('Blood_pressure', models.CharField(blank=True, max_length=6, null=True, verbose_name='Presion arterial')),
                ('Data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Datos del paciente')),
                ('Doctor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctors', verbose_name='Doctor')),
            ],
        ),
    ]
