# Generated by Django 4.1.1 on 2022-10-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('License', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growth_and_development',
            old_name='Data',
            new_name='name_patients',
        ),
        migrations.RenameField(
            model_name='vaccines',
            old_name='Data',
            new_name='name_patient',
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='Eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ips vacunadora'),
        ),
    ]
