# Generated by Django 4.1.1 on 2022-11-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('License', '0002_rename_data_growth_and_development_name_patients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='Ips',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Ips'),
        ),
        migrations.AlterField(
            model_name='growth_and_development',
            name='IMC',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Imc'),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='Eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eps vacunadora'),
        ),
    ]
