# Generated by Django 4.1.1 on 2022-11-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_alter_patients_gender'),
        ('License', '0003_vaccines_ips_alter_growth_and_development_imc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growth_and_development',
            name='name_patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Datos del paciente'),
        ),
    ]
