# Generated by Django 4.1.1 on 2022-11-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_alter_patients_gender'),
        ('License', '0004_alter_growth_and_development_name_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growth_and_development',
            name='name_patients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.patients', verbose_name='Datos del paciente'),
            preserve_default=False,
        ),
    ]
